name: update
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs at every 5th minute
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find JSON files
        id: jsonfiles
        run: |
          json_files=$(find bucket -name '*.json' -exec basename {} .json \;)
          echo "::set-output name=json_files::$json_files"

      - name: Run checkver.ps1 script
  
        run: |
          for file in ${{ steps.jsonfiles.outputs.json_files }}
          do
            pwsh -File ./bin/checkver.ps1 $file
          done
